import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { UserProfileProvider } from "@/context-api/UserProfileContext";
import AppSidebar from "@/components/app-sidebar";
import { PasswordProvider } from "@/context-api/PasswordContext";
import { CategoryProvider } from "@/context-api/CategoryContext";
import { AppProvider } from "@/context-api/AppProvider";

export const metadata = {
  title: "Protected Route",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({ children }) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      {/* <Navbar /> */}
      {/* h-full w-full flex-col gap-y-10 */}
      {/* <div className="h-[90vh] flex items-center justify-center bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-400 to-blue-800"> */}

      <AppProvider>
        {/* <UserProfileProvider> */}
        <AppSidebar>
          {/* <CategoryProvider> */}
          {/* <PasswordProvider> */}
          {children}
          {/* </PasswordProvider> */}
          {/* </CategoryProvider> */}
        </AppSidebar>
        {/* </UserProfileProvider> */}
      </AppProvider>
      {/* </div> */}
    </SessionProvider>
  );
}
